quarkus.http.port=${GUITARIST_PORT:9000}

guitarist.name=${GUITARIST_NAME:Slash}
guitarist.delay-ms=${GUITARIST_DELAY_MS:300}
guitarist.failure-ratio=${GUITARIST_FAILURE_RATIO:0}

# Auto-registration with Consul
quarkus.stork.band-service.service-registrar.type=consul
quarkus.stork.band-service.service-registrar.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.band-service.service-registrar.consul-port=${CONSUL_PORT:8500}
