quarkus.http.port=8080

# Stork — Consul service discovery
quarkus.stork.band-service.service-discovery.type=consul
quarkus.stork.band-service.service-discovery.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.band-service.service-discovery.consul-port=${CONSUL_PORT:8500}
quarkus.stork.band-service.service-discovery.refresh-period=5S

# Stork — Load balancer (change to: random, least-requests, power-of-two-choices, least-response-time, sticky)
quarkus.stork.band-service.load-balancer.type=round-robin

# Observability
quarkus.micrometer.binder.stork.enabled=true
