server.port=8081

# Stork — Consul service discovery
stork.band-service.service-discovery.type=consul
stork.band-service.service-discovery.consul-host=${CONSUL_HOST:localhost}
stork.band-service.service-discovery.consul-port=${CONSUL_PORT:8500}

# Stork — Load balancer
stork.band-service.load-balancer.type=round-robin
