quarkus.http.port=8082

# REST client — Quarkus dispatcher
quarkus.rest-client.dispatcher-quarkus.url=http://${DISPATCHER_QUARKUS_HOST:localhost}:${DISPATCHER_QUARKUS_PORT:8080}

# REST client — Spring Boot dispatcher
quarkus.rest-client.dispatcher-spring.url=http://${DISPATCHER_SPRING_HOST:localhost}:${DISPATCHER_SPRING_PORT:8081}
