quarkus.http.port=${GUITAR_HERO_PORT:9000}

guitar-hero.name=${GUITAR_HERO:Slash}
guitar-hero.delay-ms=${GUITAR_HERO_DELAY_MS:300}
guitar-hero.failure-ratio=${GUITAR_HERO_FAILURE_RATIO:0}

# Auto-registration with Consul
quarkus.stork.band-service.service-registrar.type=consul
quarkus.stork.band-service.service-registrar.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.band-service.service-registrar.consul-port=${CONSUL_PORT:8500}
