name: Basic build to ensure everything is ok

on:
  workflow_dispatch: # manual only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Stork SNAPSHOT
        run: |
          git clone https://github.com/smallrye/smallrye-stork.git /tmp/smallrye-stork
          cd /tmp/smallrye-stork
          mvn install -DskipTests -q

      - name: Build & Test
        run: mvn clean install
